[build]
    functions = "netlify/functions"
    publish = "public"
[[redirects]]
    from = "/api"
    to = "/.netlify/functions/api"
    status = 200
[dev]
    functions = "netlify/functions"
    publish = "public"
    port = 1326
    autoLaunch = true
